# Scikit-learn

This notebook discusses some of the most important functions of scikit-learn

0. An end to end scikit-learn workflow
1. Getting the data ready
2. Choose the right estimator/algorithm for our problems
3. Fit the model/algorithm and use it to make predictions on our data
4. Evaluating a model
5. Improve a model
6. Save and load a trained model
7. Putting it all together!

So let's start!

# 0. An end to end scikit-learn workflow

In [1]:
# 1. getting the data ready
import numpy as np
import pandas as pd
heart_disease= pd.read_csv("087 heart-disease.csv")
heart_disease.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [2]:
# Create X which is the features matrix
X = heart_disease.drop("target",axis=1) # drops the target column

# Create y which is the labels
y = heart_disease["target"]

In [3]:
# 2. Choose the right model and hyperparameters
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier()

# We will keep the default hyperparameters
clf.get_params() # lists all the hyperparameters

{'bootstrap': True,
 'ccp_alpha': 0.0,
 'class_weight': None,
 'criterion': 'gini',
 'max_depth': None,
 'max_features': 'sqrt',
 'max_leaf_nodes': None,
 'max_samples': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'monotonic_cst': None,
 'n_estimators': 100,
 'n_jobs': None,
 'oob_score': False,
 'random_state': None,
 'verbose': 0,
 'warm_start': False}

In [4]:
# 3. Fit the model to the training data
from sklearn.model_selection import train_test_split

# we will split the data into training data and testing samples
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25)

In [5]:
clf.fit(X_train,y_train) #train the model

RandomForestClassifier()

In [6]:
y_preds= clf.predict(X_test)
y_preds

array([1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 1, 1, 1, 1, 1, 0, 1, 1])

In [7]:
y_test

64     1
281    0
78     1
155    1
28     1
      ..
122    1
53     1
227    0
57     1
81     1
Name: target, Length: 76, dtype: int64

In [8]:
# 4.Evaluate the model
clf.score(X_train,y_train)

1.0

In [9]:
clf.score(X_test,y_test)

0.8157894736842105

In [10]:
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score

print(classification_report(y_test,y_preds))

              precision    recall  f1-score   support

           0       0.83      0.74      0.78        34
           1       0.80      0.88      0.84        42

    accuracy                           0.82        76
   macro avg       0.82      0.81      0.81        76
weighted avg       0.82      0.82      0.81        76

In [11]:
confusion_matrix(y_test,y_preds)

array([[25,  9],
       [ 5, 37]])

In [12]:
accuracy_score(y_test,y_preds)

0.8157894736842105

In [13]:
# 5.Improving the model
# try different amounts of n_estimators
# Try different numbers of estimators (trees)... (no cross-validation)
np.random.seed(42)
for i in range(100, 200, 10):
    print(f"Trying model with {i} estimators...")
    model = RandomForestClassifier(n_estimators=i).fit(X_train, y_train)
    print(f"Model accuracy on test set: {model.score(X_test, y_test) * 100:.2f}%")
    print("")

Trying model with 100 estimators...
Model accuracy on test set: 81.58%

Trying model with 110 estimators...
Model accuracy on test set: 81.58%

Trying model with 120 estimators...
Model accuracy on test set: 82.89%

Trying model with 130 estimators...
Model accuracy on test set: 81.58%

Trying model with 140 estimators...
Model accuracy on test set: 84.21%

Trying model with 150 estimators...
Model accuracy on test set: 82.89%

Trying model with 160 estimators...
Model accuracy on test set: 82.89%

Trying model with 170 estimators...
Model accuracy on test set: 82.89%

Trying model with 180 estimators...
Model accuracy on test set: 81.58%

Trying model with 190 estimators...
Model accuracy on test set: 80.26%

In [14]:
# 6. Save a model and load it
import pickle

pickle.dump(clf, open("random-forest-classifier1.pkl", "wb"))

In [15]:
loaded_model= pickle.load(open("random-forest-classifier1.pkl","rb"))
loaded_model.score(X_test,y_test)

0.8157894736842105

In [16]:
# how to suppress the warnings that appear

# import warnings
# warnings.filterwarnings("ignore")

# Not to be used all the time

In [17]:
import sklearn
sklearn.show_versions()

System:
    python: 3.10.19 (main, Oct 21 2025, 16:43:05) [GCC 11.2.0]
executable: /home/aditya/miniconda3/envs/aiml/bin/python
   machine: Linux-6.19.6-arch1-1-x86_64-with-glibc2.43

Python dependencies:
      sklearn: 1.7.2
          pip: 26.0.1
   setuptools: 80.10.2
        numpy: 2.2.6
        scipy: 1.15.2
       Cython: None
       pandas: 2.3.3
   matplotlib: 3.10.8
       joblib: 1.5.3
threadpoolctl: 3.6.0

Built with OpenMP: True

threadpoolctl info:
       user_api: blas
   internal_api: openblas
    num_threads: 12
         prefix: libopenblas
       filepath: /home/aditya/miniconda3/envs/aiml/lib/libopenblasp-r0.3.30.so
        version: 0.3.30
threading_layer: pthreads
   architecture: Haswell

       user_api: openmp
   internal_api: openmp
    num_threads: 12
         prefix: libgomp
       filepath: /home/aditya/miniconda3/envs/aiml/lib/libgomp.so.1.0.0
        version: None

# 1. Getting our data ready to be used with machine learning
    Three main things we have to do:
    1. Split the data into features and labels(usually 'X' and 'y')
    2. Filling (also called imputing) or disregarding missing values
    3. Converting non-numerical values to mumerical values(also called feature encoding)

In [18]:
heart_disease.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

In [21]:
X = heart_disease.drop("target",axis=1)
X.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2

In [23]:
y = heart_disease["target"]
y.head()

0    1
1    1
2    1
3    1
4    1
Name: target, dtype: int64

In [29]:
# now splitting the data into training and test datasets
# from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2)

len(X),len(X_train),len(X_test)

(303, 242, 61)

### 1.1 Make sure that its all numerical

In [33]:
car_sales = pd.read_csv("car-sales-extended.csv")
car_sales.head()

     Make Colour  Odometer (KM)  Doors  Price
0   Honda  White          35431      4  15323
1     BMW   Blue         192714      5  19943
2   Honda  White          84714      4  28343
3  Toyota  White         154365      4  13434
4  Nissan   Blue         181577      3  14043

In [32]:
len(car_sales)

1000

In [38]:
X = car_sales.drop("Price",axis=1)
X.head()

     Make Colour  Odometer (KM)  Doors
0   Honda  White          35431      4
1     BMW   Blue         192714      5
2   Honda  White          84714      4
3  Toyota  White         154365      4
4  Nissan   Blue         181577      3

In [41]:
y = car_sales["Price"]
y.head()

0    15323
1    19943
2    28343
3    13434
4    14043
Name: Price, dtype: int64